name: Build And Push Container Image

on:
  push:
    branches:
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: type4ny

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    if: github.repository == 'type4ny-project/type4ny'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/type4ny-project/type4ny
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare image tags
        run: |
          echo "FORMATTED_BRANCH_NAME=$(echo ${{ github.ref_name }} | sed -e 's/\//-/g' )" >> $GITHUB_ENV
      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }}
          provenance: false
          labels: ${{ env.FORMATTED_BRANCH_NAME }}
          cache-from: type=registry,ref=ghcr.io/type4ny-project/type4ny:io-buildcache
          cache-to: type=registry,ref=ghcr.io/type4ny-project/type4ny:io-buildcache,mode=max
          tags: |
            ghcr.io/type4ny-project/type4ny:latest
            ghcr.io/type4ny-project/type4ny:${{ env.FORMATTED_BRANCH_NAME }}

# https://github.com/MisskeyIO/misskey/blob/io/.github/workflows/docker-io.yml
